# Generated by Django 4.1.1 on 2022-09-26 15:17

import ckeditor.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beats',
            fields=[
                ('beats_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('descrip', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='christ.png', null=True, upload_to='beat_image')),
                ('beats', models.FileField(blank=True, null=True, upload_to='beats_songs')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Beats',
                'verbose_name_plural': 'Beats',
                'db_table': 'beats',
                'managed': True,
            },
        ),
    ]
