# Generated by Django 4.1.1 on 2022-09-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beats',
            name='subname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
