# Generated by Django 4.1.1 on 2022-09-27 04:34

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('beats', '0004_remove_album_beats_album_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, default='christ.png', null=True, upload_to='album_image')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('catalog', models.CharField(blank=True, max_length=100, null=True)),
                ('beat_format', models.CharField(blank=True, max_length=100, null=True)),
                ('descrip', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'db_table': 'album',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Album_beats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('subname', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, default='christ.png', null=True, upload_to='album_beats')),
                ('beats', models.FileField(blank=True, null=True, upload_to='album_beats')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('album_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beats.album')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Album_beats',
                'verbose_name_plural': 'Album_beats',
                'db_table': 'album_beats',
                'managed': True,
            },
        ),
    ]
