# Generated by Django 4.1.1 on 2022-10-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0006_number_beat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album_beats',
            name='album_name',
        ),
        migrations.RemoveField(
            model_name='album_beats',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='beats',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='number_beat',
            name='created_beats',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Album_beats',
        ),
        migrations.DeleteModel(
            name='Beats',
        ),
        migrations.DeleteModel(
            name='Number_beat',
        ),
    ]
