# Generated by Django 4.1.1 on 2022-10-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0011_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pics',
            field=models.ImageField(default='static/christ.png', upload_to=''),
        ),
    ]
