# Generated by Django 4.1.1 on 2022-10-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0012_alter_comment_pics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beats',
            name='album_name',
        ),
        migrations.RemoveField(
            model_name='beats',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_beat',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='number_beat',
            name='created_beats',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Beats',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Number_beat',
        ),
    ]
