# Generated by Django 4.1.1 on 2022-10-18 06:04

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
        ('beats', '0013_remove_beats_album_name_remove_beats_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, default='christ.png', null=True, upload_to='album_image')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('catalog', models.CharField(blank=True, max_length=100, null=True)),
                ('beat_format', models.CharField(blank=True, max_length=100, null=True)),
                ('descrip', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'db_table': 'album',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Beats',
            fields=[
                ('beats_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('subname', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('descrip', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='christ.png', null=True, upload_to='beat_image')),
                ('beats', models.FileField(blank=True, null=True, upload_to='beats_songs')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('album_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beats.album')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Beats',
                'verbose_name_plural': 'Beats',
                'db_table': 'beats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Number_beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_beats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beats.beats')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('pics', models.ImageField(default='static/christ.png', upload_to='')),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment_beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='beats.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
