# Generated by Django 4.1.1 on 2022-10-19 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0014_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='playsong_com',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listbeat', to='beats.beats'),
        ),
    ]
