# Generated by Django 4.1.1 on 2022-10-20 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0015_comment_playsong_com'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_beat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='beats.album'),
        ),
    ]
