# Generated by Django 4.1.1 on 2022-10-21 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0016_alter_comment_comment_beat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number_album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_albums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beats.album')),
            ],
        ),
    ]
