# Generated by Django 4.1.1 on 2022-10-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0018_categories_album_category_beats_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='category',
            field=models.CharField(blank=True, choices=[('Gbeduboss', 'Gbeduboss'), ('Dina', 'Dina'), ('Tiffy', 'Tiffy'), ('Pop', 'Pop'), ('Afrobeat', 'Afrobeat'), ('Junky', 'Junky'), ('Featured', 'Featured'), ('Free Download', 'Free Download'), ('Hot New !', 'Hot New !')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beats',
            name='category',
            field=models.CharField(blank=True, choices=[('Gbeduboss', 'Gbeduboss'), ('Dina', 'Dina'), ('Tiffy', 'Tiffy'), ('Pop', 'Pop'), ('Afrobeat', 'Afrobeat'), ('Junky', 'Junky'), ('Featured', 'Featured'), ('Free Download', 'Free Download'), ('Hot New !', 'Hot New !')], max_length=100, null=True),
        ),
    ]
