# Generated by Django 4.1.1 on 2022-10-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0020_all_artist_genre_album_artist_album_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beats',
            name='buy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beats',
            name='freedownload',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beats',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
