# Generated by Django 4.1.1 on 2022-12-09 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0023_delete_all_artist_delete_genre_remove_album_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beats.categories'),
        ),
        migrations.AddField(
            model_name='beats',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beats.categories'),
        ),
    ]
