# Generated by Django 4.1.1 on 2022-10-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatcart', '0002_alter_beatscart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatscart',
            name='session_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
