# Generated by Django 4.1.1 on 2022-10-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatcart', '0003_beatscart_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatscart',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
