# Generated by Django 4.1.1 on 2022-11-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatcart', '0006_checkout_ship_paidorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatscart',
            name='total',
            field=models.IntegerField(),
        ),
    ]
