# Generated by Django 4.1.1 on 2022-11-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatcart', '0007_alter_beatscart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatscart',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
