# Generated by Django 4.1.1 on 2022-11-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatcart', '0008_alter_beatscart_total'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='beatscart',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='beatscart',
            name='album',
        ),
        migrations.RemoveField(
            model_name='beatscart',
            name='beat',
        ),
        migrations.RemoveField(
            model_name='beatscart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
        migrations.RemoveField(
            model_name='paidorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='album',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='beat',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='user',
        ),
        migrations.DeleteModel(
            name='Beatscart',
        ),
        migrations.DeleteModel(
            name='Paidorder',
        ),
        migrations.DeleteModel(
            name='Ship',
        ),
    ]
