# Generated by Django 4.1.1 on 2022-11-10 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beats', '0022_beats_display'),
        ('beatcart', '0009_alter_beatscart_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=70, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordr_no', models.CharField(max_length=50)),
                ('things_bought', models.CharField(blank=True, max_length=500, null=True)),
                ('itm_paid', models.BooleanField(default=False)),
                ('total', models.FloatField()),
                ('firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beats.album')),
                ('beat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beats.beats')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paidorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('cart_no', models.CharField(blank=True, max_length=36, null=True)),
                ('payment_code', models.CharField(max_length=50)),
                ('paid_item', models.BooleanField(default=False)),
                ('firstname', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Beatscart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('beat_name', models.CharField(max_length=100)),
                ('total', models.IntegerField(default=1)),
                ('order_no', models.CharField(max_length=50)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('item_paid', models.BooleanField(default=False)),
                ('beat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beats.beats')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'session_id')},
            },
        ),
        migrations.CreateModel(
            name='Albumcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('beat_name', models.CharField(max_length=100)),
                ('total', models.IntegerField(default=1)),
                ('order_no', models.CharField(max_length=50)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('item_paid', models.BooleanField(default=False)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beats.album')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'session_id')},
            },
        ),
    ]
