# Generated by Django 4.1.1 on 2022-11-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatcart', '0010_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatscart',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
