# Generated by Django 4.1.1 on 2022-09-25 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_header', models.CharField(blank=True, max_length=100, null=True)),
                ('third_subheader', models.CharField(blank=True, max_length=100, null=True)),
                ('link_one', models.URLField(blank=True, null=True)),
                ('link_name', models.CharField(blank=True, max_length=100, null=True)),
                ('link_two', models.URLField(blank=True, null=True)),
                ('forth_header', models.CharField(blank=True, max_length=100, null=True)),
                ('forth_subheader', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Advert',
                'verbose_name_plural': 'Adverts',
                'db_table': 'advert',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_word', models.CharField(blank=True, max_length=200, null=True)),
                ('second_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'banner',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('subname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'db_table': 'newsletter',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_one', models.CharField(blank=True, max_length=50, null=True)),
                ('small_header', models.CharField(blank=True, max_length=50, null=True)),
                ('service_image', models.ImageField(blank=True, default='phone.jpg', null=True, upload_to='services_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Subname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subdescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbeduboss.subname')),
            ],
            options={
                'verbose_name': 'Subdescription',
                'verbose_name_plural': 'Subdescriptions',
                'db_table': 'subdescription',
                'managed': True,
            },
        ),
    ]
