# Generated by Django 4.1.1 on 2022-09-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbeduboss', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
