# Generated by Django 4.1.1 on 2022-09-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbeduboss', '0003_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
