# Generated by Django 4.1.1 on 2022-09-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbeduboss', '0004_delete_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_one', models.CharField(blank=True, max_length=50, null=True)),
                ('small_header', models.CharField(blank=True, max_length=50, null=True)),
                ('service_image', models.ImageField(blank=True, default='phone.jpg', null=True, upload_to='services_pics')),
            ],
        ),
    ]
