# Generated by Django 4.1.1 on 2022-09-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbeduboss', '0005_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subdescription',
        ),
        migrations.DeleteModel(
            name='Subname',
        ),
    ]
