# Generated by Django 4.1.1 on 2022-09-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbeduboss', '0007_subname_subdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='link_nam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
